### ISSUE TITLE
jdk21 JMockit 1.54  Caused by: java.lang.IllegalStateException: JMockit didn't get initialized; please check the -javaagent JVM initialization parameter was use

### ISSUE THREAD

**Issue by Czytx** [hazendaz/jmockit1#263]
Please provide the following information:

* Version of JMockit that was used: 

* Description of the problem or enhancement request:

* Check the following:

 - [ ] If a defect or unexpected result, JMockit project members should be able to reproduce it.
  For that, include an example test (perhaps accompanied by a Maven/Gradle build script) which
  can be executed without changes and reproduces the failure.

 - [ ] If an enhancement or new feature request, it should be justified by an example test
  demonstrating the validity and usefulness of the desired enhancement or new feature.

 - [ ] The issue does not fall outside the scope of the project (for example, attempting to use
  JMockit APIs from Groovy or Scala code, or with an Android runtime).

 - [ ] The JDK where the problem occurs is a final release, not a development build.

**Comment by hazendaz** [comment]
Did you setup the agent?  Look at the project poms here, this runs on jdk 21 without issue, higher even.

**Comment by Czytx** [comment]
> Did you setup the agent? Look at the project poms here, this runs on jdk 21 without issue, higher even.

No agent set up

**Comment by hazendaz** [comment]
It will not work unless you set the agent up.

In your pom assuming you are using maven

```
        <!-- Surefire Argline -->
        <argLine>-javaagent:${settings.localRepository}/com/github/hazendaz/jmockit/jmockit/1.54.0/jmockit-1.54.0.jar</argLine>
```

**Comment by Czytx** [comment]
> It will not work unless you set the agent up.
> 
> In your pom assuming you are using maven
> 
> ```
>         
>         <argLine>-javaagent:${settings.localRepository}/com/github/hazendaz/jmockit/jmockit/1.54.0/jmockit-1.54.0.jar</argLine>
> ```

ths
